version: "3.7"
services:
  # prod
  scout:
    image: "scout:production"
    container_name: scout
    build:
      target: production
    ports:
      - 3000
    volumes:
      - ./:/app
    environment:
      NODE_ENV: production

  # dev
  scout-dev:
    image: "scout:development"
    container_name: scout-dev
    build:
      target: development
    ports:
      - 3000
    volumes:
      - ./:/app:cached
    environment:
      NODE_ENV: development
